// Generated by Wrangler on Sat Apr 27 2024 21:27:30 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	EXPECTED_FROM_EMAIL: "";
	FROM_EMAIL: "";
	TO_EMAIL: "";
	SEB: SendEmail;
	AI: unknown;
}
